--create table polygon_type (
--    id int GENERATED BY DEFAULT AS IDENTITY(START WITH 0),
--    -- starting id with 0 to match Java enum PolygonType
--    polygon_type_name varchar(30) not null,
--    primary key (id)
--    );
--
--insert into polygon_type (polygon_type_name) values ('CTR');
--insert into polygon_type (polygon_type_name) values ('TMA');
--insert into polygon_type (polygon_type_name) values ('SID');
--insert into polygon_type (polygon_type_name) values ('STAR');
--insert into polygon_type (polygon_type_name) values ('VFR');
--insert into polygon_type (polygon_type_name) values ('FIX');
--insert into polygon_type (polygon_type_name) values ('RIVER');
--insert into polygon_type (polygon_type_name) values ('TOWN');
--insert into polygon_type (polygon_type_name) values ('ROAD');
--insert into polygon_type (polygon_type_name) values ('TSA');
--insert into polygon_type (polygon_type_name) values ('TRA');
--insert into polygon_type (polygon_type_name) values ('AREA');
--insert into polygon_type (polygon_type_name) values ('P');
--insert into polygon_type (polygon_type_name) values ('R');
--insert into polygon_type (polygon_type_name) values ('D');
--insert into polygon_type (polygon_type_name) values ('UNDEFINED');



create table polygon (
    id int not null auto_increment,
    polygon_name varchar(30) not null,
    polygon_type_id int not null,
    primary key (id)
    -- foreign key (polygon_type_id) references polygon_type(id)
    );

insert into polygon (polygon_name, polygon_type_id) values ('CTR', 0);
insert into polygon (polygon_name, polygon_type_id) values ('TMA_A', 1);
insert into polygon (polygon_name, polygon_type_id) values ('TMA_B', 1);
insert into polygon (polygon_name, polygon_type_id) values ('TMA_C', 1);
insert into polygon (polygon_name, polygon_type_id) values ('TMA_D', 1);