--create table polygon_type (
--    id int GENERATED BY DEFAULT AS IDENTITY(START WITH 0),
--    -- starting id with 0 to match Java enum PolygonType
--    polygon_type_name varchar(30) not null,
--    primary key (id)
--    );
--
--insert into polygon_type (polygon_type_name) values ('CTR');
--insert into polygon_type (polygon_type_name) values ('TMA');
--insert into polygon_type (polygon_type_name) values ('SID');
--insert into polygon_type (polygon_type_name) values ('STAR');
--insert into polygon_type (polygon_type_name) values ('VFR');
--insert into polygon_type (polygon_type_name) values ('FIX');
--insert into polygon_type (polygon_type_name) values ('RIVER');
--insert into polygon_type (polygon_type_name) values ('TOWN');
--insert into polygon_type (polygon_type_name) values ('ROAD');
--insert into polygon_type (polygon_type_name) values ('TSA');
--insert into polygon_type (polygon_type_name) values ('TRA');
--insert into polygon_type (polygon_type_name) values ('AREA');
--insert into polygon_type (polygon_type_name) values ('P');
--insert into polygon_type (polygon_type_name) values ('R');
--insert into polygon_type (polygon_type_name) values ('D');
--insert into polygon_type (polygon_type_name) values ('UNDEFINED');



create table polygon (
    id int not null auto_increment,
    polygon_name varchar(30) not null,
    polygon_type_id int not null,
    primary key (id)
    -- foreign key (polygon_type_id) references polygon_type(id)
    );

insert into polygon (polygon_name, polygon_type_id) values ('EPSYCTR', 0);
insert into polygon (polygon_name, polygon_type_id) values ('EPSYTMA_A', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPSYTMA_B', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPSYTMA_C', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPSYTMA_D', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPGDTMA_TOP', 1);

insert into polygon (polygon_name, polygon_type_id) values ('TSA02A', 10);
insert into polygon (polygon_name, polygon_type_id) values ('TSA02B', 10);
insert into polygon (polygon_name, polygon_type_id) values ('TSA02C', 10);
insert into polygon (polygon_name, polygon_type_id) values ('TSA02D', 10);
insert into polygon (polygon_name, polygon_type_id) values ('TSA02E', 10);
insert into polygon (polygon_name, polygon_type_id) values ('TSA02F', 10);

insert into polygon (polygon_name, polygon_type_id) values ('BORDER', 9);

insert into polygon (polygon_name, polygon_type_id) values ('TSA01A', 10);
insert into polygon (polygon_name, polygon_type_id) values ('TSA01B', 10);
insert into polygon (polygon_name, polygon_type_id) values ('TSA01C', 10);


insert into polygon (polygon_name, polygon_type_id) values ('EPGDCTR', 0);
insert into polygon (polygon_name, polygon_type_id) values ('EPSCCTR', 0);
insert into polygon (polygon_name, polygon_type_id) values ('EPBYCTR', 0);
insert into polygon (polygon_name, polygon_type_id) values ('EPMOCTR', 0);
insert into polygon (polygon_name, polygon_type_id) values ('EPWACTR', 0);
insert into polygon (polygon_name, polygon_type_id) values ('EPPOCTR', 0);
insert into polygon (polygon_name, polygon_type_id) values ('EPWRCTR', 0);
insert into polygon (polygon_name, polygon_type_id) values ('EPKTCTR', 0);
insert into polygon (polygon_name, polygon_type_id) values ('EPKKCTR', 0);
insert into polygon (polygon_name, polygon_type_id) values ('EPLLCTR', 0);
insert into polygon (polygon_name, polygon_type_id) values ('EPLBCTR', 0);
insert into polygon (polygon_name, polygon_type_id) values ('EPRZCTR', 0);

insert into polygon (polygon_name, polygon_type_id) values ('EPWATMA_A', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPWATMA_B', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPWATMA_C', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPWATMA_D', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPWATMA_E', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPWATMA_F', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPWATMA_G', 1);

insert into polygon (polygon_name, polygon_type_id) values ('EPLBTMA_A', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPLBTMA_B', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPLBTMA_C', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPLBTMA_D', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPLBTMA_E', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPLBTMA_F', 1);

insert into polygon (polygon_name, polygon_type_id) values ('EPBYTMA_A', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPBYTMA_B', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPBYTMA_C', 1);

insert into polygon (polygon_name, polygon_type_id) values ('EPKKTMA_TOP', 1);

insert into polygon (polygon_name, polygon_type_id) values ('EPLLTMA_A', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPLLTMA_B', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPLLTMA_C', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPLLTMA_D', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPLLTMA_E', 1);

insert into polygon (polygon_name, polygon_type_id) values ('EPPOTMA_NORTH', 1);
insert into polygon (polygon_name, polygon_type_id) values ('EPPOTMA_SOUTH', 1);

insert into polygon (polygon_name, polygon_type_id) values ('EPRATMA_TOP', 1);

insert into polygon (polygon_name, polygon_type_id) values ('EPRZTMA_TOP', 1);

insert into polygon (polygon_name, polygon_type_id) values ('EPSCTMA_TOP', 1);

insert into polygon (polygon_name, polygon_type_id) values ('EPZGTMA', 1);














